### ISSUE TITLE
Object.fromEntries is not a function

### ISSUE THREAD

**Issue by canvasandcode** [jammeryhq/gridsome-starter-liebling#2]
Hi, I created a new project based on the instructions, but when I run **gridsome develop** I get the following error in my terminal:

```
TypeError: Object.fromEntries is not a function
    at collectionStore.data.map.node (/Users/imran.rahman/Documents/gridsome/my-blog/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:70:34)
    at Array.map (<anonymous>)
    at getStoreCollection (/Users/imran.rahman/Documents/gridsome/my-blog/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:65:35)
    at collection (/Users/imran.rahman/Documents/gridsome/my-blog/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:134:14)
    at /Users/imran.rahman/Documents/gridsome/my-blog/node_modules/gridsome-plugin-flexsearch/node_modules/p-map/index.js:57:28
```

I'm not sure what is causing this, but I'm unable to use the starter due to this, any ideas what is causing the issue?

Thanks in advance.

**Comment by canvasandcode** [comment]
Ok, it looks like my version of node was outdated which was causing the issue, I have upgraded to the latest stable version and now the error no longer displays. Closing this ticket.
