### ISSUE TITLE
gridsome-plugin-flexsearch error

### ISSUE THREAD

**Issue by nbnotabene** [jammeryhq/gridsome-starter-liebling#8]
Thank You - Very nice starter

Problem: I can only start system if I disable (remove) plugin-flexsearch. If not ......

\#> gridsome develop
-----------------------------------------------------
Gridsome v0.7.21

Initializing plugins...
Load sources - 0.09s
Create GraphQL schema - 0.09s
Create pages and templates - 0.06s
Generate temporary code - 0.04s
TypeError: Object.fromEntries is not a function
    at collectionStore.data.map.node (/home/nb/project/myGridsome/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:70:34)
    at Array.map (<anonymous>)
    at getStoreCollection (/home/nb/project/myGridsome/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:65:35)
    at collection (/home/nb/project/myGridsome/node_modules/gridsome-plugin-flexsearch/gridsome.server.js:134:14)
    at /home/nb/project/myGridsome/node_modules/gridsome-plugin-flexsearch/node_modules/p-map/index.js:57:28

**Comment by noxify** [comment]
Hey @nbnotabene 

Thanks for reporting.

Did you changed something in the `gridsome.configure.js`?

Or is it not working directly after using `gridsome create ...`

**Comment by nbnotabene** [comment]
Solved: 
I failed to realize that flexsearch requires node >= v12
Thanks again!
